version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: fcfd0f62549a
    mac_address: 02:42:ac:11:00:02
    environment:
      - PATH=/opt/rabbitmq/sbin:/opt/erlang/bin:/opt/openssl/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ERLANG_INSTALL_PATH_PREFIX=/opt/erlang
      - OPENSSL_INSTALL_PATH_PREFIX=/opt/openssl
      - RABBITMQ_DATA_DIR=/var/lib/rabbitmq
      - RABBITMQ_VERSION=3.13.7
      - RABBITMQ_PGP_KEY_ID=0x0A9AF2115F4687BD29803A206B73A36E6026DFCA
      - RABBITMQ_HOME=/opt/rabbitmq
      - HOME=/var/lib/rabbitmq
      - LANG=C.UTF-8
      - LANGUAGE=C.UTF-8
      - LC_ALL=C.UTF-8
    volumes:
      - /var/lib/rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: "no"
    labels:
      org.opencontainers.image.ref.name: "ubuntu"
      org.opencontainers.image.version: "22.04"
    networks:
      - bridge

networks:
  bridge:
    driver: bridge